# This is a basic workflow to help you get started with Actions

name: Sample workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: "Name"
        description: "name input"
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Say hello
        run: echo Hello, ${{inputs.name}}!
  check-versions:
    runs-on: self-hosted
    steps:
      - name: Check node version
        run: node --version
